version: "3.8"
services:
  backend-oneclickinsight:
    container_name: backend-oneclickinsight
    build:
      context: ../Ailyze_openai_dajngo/AILYZE/
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db 
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    depends_on:
      - db
    networks:
      ailyze-nw:
    volumes:
    #Resolve this
      - ../../Ailyze_openai_dajngo/AILYZE:/AILYZE
    env_file:
      - ./.env
    command: sh -c "ls &&  python AILYZE/manage.py migrate && daphne -u AILYZE -p 8001"
    