version: "3.8"
services:
  backend-oneclickinsight:
    container_name: backend-oneclickinsight
    build:
      context: ../Ailyze_openai_dajngo/AILYZE/
    ports:
      - "8001:8001"
    environment:
      DB_HOST: db 
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      CELERY_BROKER_URL: "amqp://staginguser:stagingpassword@rabbitmq:5672//"
    depends_on:
      - db
    networks:
      ailyze-nw:
    volumes:
      - ../Ailyze_openai_dajngo/AILYZE:/AILYZE
    env_file:
      - ./.env
    command: sh -c "ls AILYZE && python manage.py migrate && python manage.py runserver 0.0.0.0:8001"

