version: "3.8"
services:
  backend-chatbot:
    container_name: backend-chatbot
    build:
      context: ../Ailyze_openai_dajngo/AILYZE/
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      CELERY_BROKER_URL: "amqp://staginguser:stagingpassword@rabbitmq:5672//"
    networks:
      ailyze-nw:
    volumes:
      - ../Ailyze_openai_dajngo/AILYZE:/AILYZE
    env_file:
      - ./.env
    command: sh -c "ls && gunicorn --bind 0.0.0.0:8000 --timeout 300 --access-logfile - --error-logfile - AILYZE.wsgi"