version: '3.8'
services:
  frontend:
    container_name: frontend
    build:
      context: ../ailyze-nextjs
    ports:
      - "3020:3020"
    environment:
      - "REACT_APP_BASE_URL=https://xyz.weuselinux.com/api"
      - "REACT_APP_PUBLIC_URL=http://localhost:3020"
      - "REACT_APP_API_URL=https://xyz.weuselinux.com"
    networks:
      ailyze-nw:
    stdin_open: true
    volumes:
      - ../ailyze-nextjs:/app
    command: sh -c "ls && pm2 startup && pm2 monitor"
