version: "3.8"
services:
  celery:
    container_name: celery
    restart: on-failure
    build:
      context: ../Ailyze_openai_dajngo/AILYZE/
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    volumes:
      - ../Ailyze_openai_dajngo/AILYZE:/AILYZE
    env_file:
      - ./.env
    command: celery  -A AILYZE worker -l info
    depends_on:
      - redis
      - backend-oneclickinsight
    networks:
      ailyze-nw:
  
  celery-beat:
    container_name: celery_beat
    build:
      context: ../Ailyze_openai_dajngo/AILYZE/
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    volumes:
      - ../Ailyze_openai_dajngo/AILYZE:/AILYZE
    env_file:
      - ./.env
    command: celery -A AILYZE beat -l info
    depends_on:
      - redis
      - backend-oneclickinsight
    networks:
      ailyze-nw: